default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ravena_bank_development

test:
  <<: *default
  database: ravena_bank_test

production:
  <<: *default
  database: ravena_bank_production
  username: ravena_bank
  password: <%= ENV['RAVENA_BANK_DATABASE_PASSWORD'] %>
